### ISSUE TITLE
Add persistent URL pickers next to headings in body text (like FHIR doc)

### ISSUE THREAD

**Issue by atalagk** [openEHR/spec-publish-asciidoc#14]
As discussed in GoTo meeting on 29 Jul 2015. This is in addition to existing URLs in TOC.

**Comment by wolandscat** [comment]
I discovered Asciidoctor supports this out of the box. I have published the Archetype docs (ADL2, AOM2 etc) through as far as www2 with it on. If you look at the latest diffs in specifications-AM, you'll see how easy it is. Very easy to turn on for all specs.

**Comment by wolandscat** [comment]
This is now routinely turned on.
