### ISSUE TITLE
Make root package for UML extractor settable

### ISSUE THREAD

**Issue by wolandscat** [openEHR/spec-publish-asciidoc#20]
Currently the root package for the UML extractor is assumed to be 'openehr', as per [this code](https://github.com/openEHR/spec-publish-asciidoc/blob/master/uml_extract/OpenEhrModelExporter/src/org/openehr/docs/magicdraw/OpenEHRProjectExporter.java#L26).

Can we have this as a command line option, so that the extractor will work with class models that might not have a parent package called 'openehr'. It probably needs to allow for multiple parent packages.

**Comment by bostjanl** [comment]
Added parameter -r, set to 'openehr' by default.
