### ISSUE TITLE
Adjustments to index extractor

### ISSUE THREAD

**Issue by wolandscat** [openEHR/spec-publish-asciidoc#21]
Following discussion, the following generated adoc code would work nicely.

```
==== Package common

[.xcode]
* http://www.openehr.org/releases/RM/latest/common.html#_archetyped_class[ARCHETYPED]
[.xcode]
* http://www.openehr.org/releases/RM/latest/common.html#_attestation_class[ATTESTATION]
[.xcode]
* http://www.openehr.org/releases/RM/latest/common.html#_audit_details_class[AUDIT_DETAILS]
[.xcode]

etc
```

Additionally, the extractor needs to take care of a couple of exceptions we missed first time round:
- package `rm.composition` => document 'ehr' (i.e. 'ehr.html')
- package `rm.security` => no document - ignore this package - was never impl'd in 1.0.2

**Comment by wolandscat** [comment]
Slight further fix needed. Currently, various UML classes whose name is a concrete generic type are coming out in the index, but they should be ignored. Example

![image](https://cloud.githubusercontent.com/assets/1481744/11720377/d9304c7c-9f56-11e5-86e0-10447198bf91.png)

Any class with a name containing `<>` can be ignored universally in the extractor, because we don't include them in the docs either. Due to this, in the index, they create links that don't point anywhere useful.

**Comment by bostjanl** [comment]
Fixed

**Comment by wolandscat** [comment]
Sorry - still needs a final adjustment - there are a few other classes with <>, so the filter should include something like `not className.hasChar('<')` .

**Comment by bostjanl** [comment]
Now really, really done :-)
