### ISSUE TITLE
Use release variable in index extractor output

### ISSUE THREAD

**Issue by wolandscat** [openEHR/spec-publish-asciidoc#23]
Currently the extractor generates text like this for each class:

```
[.xcode]
* http://www.openehr.org/releases/RM/latest/common.html#_archetyped_class[ARCHETYPED]
```

I've made the release a variable, so that we can make these URLs release-specific (otherwise they just point to the latest baseline, which is wrong for a specific release). Can the output be adjusted to the following:

```
[.xcode]
* http://www.openehr.org/releases/RM/{release}/common.html#_archetyped_class[ARCHETYPED]
```

i.e. `{release}` instead of `latest`.

**Comment by bostjanl** [comment]
This already works, just use -i {release}.
